#swiftmailer:
#    url: '%env(MAILER_URL)%'
#    spool: { type: 'memory' }
#    stream_options:
#        tls:
#            allow_self_signed: true
#            verify_peer: false
#            verify_peer_name: false


swiftmailer:
#    url: '%env(MAILER_URL)%'
    transport:      "%mailer_transport%"
    host:           "%mailer_host%"
    username:       "%mailer_user%"
    password:       "%mailer_password%"
    auth_mode:      "%mailer_auth_mode%"
    port:           "%mailer_port%"

#    host:             localhost
#    transport:        gmail
#    username:         luiggiplasencia0823@gmail.com
#    password:         kxvuzbdyfdvbvzil
#    host:             localhost


#    port:             587
#    encryption:       tls
#    auth-mode:        login
#    spool: { type: 'memory' }
#    stream_options:
#        ssl:
#            allow_self_signed: true
#            verify_peer: false
#            verify_peer_name: false
